// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsWiAYbo458etXyViMRm6Lplauu9DFOAQ',
    appId: '1:143115818484:web:d4446868d8884c0b91d5a1',
    messagingSenderId: '143115818484',
    projectId: 'applicant-showcase-symmetry',
    authDomain: 'applicant-showcase-symmetry.firebaseapp.com',
    storageBucket: 'applicant-showcase-symmetry.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpX2QtP967PMajt2CEuzGeJV7rLm-o8NI',
    appId: '1:143115818484:android:d82ff9d84236acd491d5a1',
    messagingSenderId: '143115818484',
    projectId: 'applicant-showcase-symmetry',
    storageBucket: 'applicant-showcase-symmetry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFFL7eZtgLCgOrHd4zE8oldnW8Cmz-yt4',
    appId: '1:143115818484:ios:a7a7596ef41a2a7691d5a1',
    messagingSenderId: '143115818484',
    projectId: 'applicant-showcase-symmetry',
    storageBucket: 'applicant-showcase-symmetry.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
